apiVersion: v1
kind: Service
metadata:
  name: kanban-backend-service
spec:
  type: NodePort
  selector:
    app: kanban-backend
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30080
